apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: clusters
    repoURL: 'https://github.com/lukasz-bielinski/automated-infra-clusters.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - PruneLast=true        
